---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/app-menu: development
    fabric8.io/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-devops/nexus/src/main/fabric8/icon.png"
  labels:
    expose: "true"
    preview: "true"
  name: artifact-repository
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8081